name: Deploy to Review Environment

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GCR_JSON_KEY }}
        export_default_credentials: true

    - name: Login to Google Container Registry
      uses: docker/login-action@v1 
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/${{ secrets.PROJECT_ID }}/streamlit-app:${{ github.event.pull_request.number }}

    - name: Deploy to Cloud Run using gcloud
      if: github.event.action != 'closed'
      id: deploy
      run: |
        URL=$(gcloud run deploy streamlit-app-pr-${{ github.event.pull_request.number }} \
          --image gcr.io/${{ secrets.PROJECT_ID }}/streamlit-app:${{ github.event.pull_request.number }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --format="value(status.url)")
        echo "DEPLOYED_URL=$URL" >> $GITHUB_ENV

    - name: Run ZAP Scan
      if: github.event.action != 'closed'
      uses: zaproxy/action-full-scan@v0.2.0
      with:
        target: ${{ env.DEPLOYED_URL }}

    - name: Delete service
      if: github.event.action == 'closed'
      run: |
        gcloud run services delete streamlit-app-pr-${{ github.event.pull_request.number }} --platform managed --region us-central1 --quiet
      env:
        GCLOUD_PROJECT_ID: ${{ secrets.PROJECT_ID }}
        GCLOUD_AUTH: ${{ secrets.GCR_JSON_KEY }}

    - name: Comment PR
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GH_PAT }}
        script: |
          const issue_number = context.issue.number;
          const url = `https://${{ env.DEPLOYED_URL }}`;
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue_number,
            body: `🚀 Your preview environment has been deployed!\n\nYou can access it here: ${url}`
          });
