name: Deploy to Review Environment

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Container Registry
      uses: docker/login-action@v1 
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/${{ secrets.PROJECT_ID }}/streamlit-app:${{ github.event.pull_request.number }}

    - name: Deploy to Cloud Run
      id: deploy
      if: github.event.action != 'closed'
      uses: google-github-actions/deploy-cloudrun@main
      with:
        service: streamlit-app-pr-${{ github.event.pull_request.number }}
        image: gcr.io/${{ secrets.PROJECT_ID }}/streamlit-app:${{ github.event.pull_request.number }}
        credentials: ${{ secrets.GCR_JSON_KEY }}

    - name: Delete service
      if: github.event.action == 'closed'
      run: |
        gcloud run services delete streamlit-app-pr-${{ github.event.pull_request.number }} --platform managed --region us-central1 --quiet
      env:
        GCLOUD_PROJECT_ID: ${{ secrets.PROJECT_ID }}
        GCLOUD_AUTH: ${{ secrets.GCR_JSON_KEY }}
